### ISSUE TITLE
Two stray tilde characters

### ISSUE THREAD

**Issue by h6w** [imeraj/erlang_playground#1]
Hi,

This doesn't compile out of the box because there are two stray tilde characters here.

https://github.com/imeraj/erlang_playground/blob/59624978bbd5bf2db2b47ed8b4573e62e671cb8d/elixirapp/src/elixirapp_app.erl#L26

Once I removed these the app worked perfectly.  Thanks!

**Comment by imeraj** [comment]
Hi @h6w,

I removed extra characters. Thanks for reporting.
